/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./components/layouts/BaseFooter.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    ChallengeCategory: typeof import('./components/ChallengeCategory.vue')['default']
    ChallengeComment: typeof import('./components/ChallengeComment.vue')['default']
    ChallengeList: typeof import('./components/ChallengeList.vue')['default']
    ChallengeProfile: typeof import('./components/ChallengeProfile.vue')['default']
    ChallengeSourceCard: typeof import('./components/ChallengeSourceCard.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    JoinRequest: typeof import('./components/JoinRequest.vue')['default']
    MyTeamCardInfo: typeof import('./components/MyTeamCardInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolveRecord: typeof import('./components/SolveRecord.vue')['default']
    TagSearch: typeof import('./components/TagSearch.vue')['default']
    TeamCardInfo: typeof import('./components/TeamCardInfo.vue')['default']
    TeamIntroduction: typeof import('./components/TeamIntroduction.vue')['default']
    TeamList: typeof import('./components/TeamList.vue')['default']
    TeamMember: typeof import('./components/TeamMember.vue')['default']
    TeamProfile: typeof import('./components/TeamProfile.vue')['default']
    TextSearch: typeof import('./components/TextSearch.vue')['default']
    UserProfile: typeof import('./components/UserProfile.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
